config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'

  resources :tickets, except: [:edit, :update]
  resource :search, only: [:show, :create]

  namespace :admin do
    resources :trains do
      resources :wagons, shallow: true
    end

    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_arrive_departure, on: :member
    end

    get 'admin/index'
    resources :tickets
    resources :routes
    resources :economy, controller: 'wagons', type: 'Economy'
    resources :comfort, controller: 'wagons', type: 'Comfort'
    resources :super_economy, controller: 'wagons', type: 'SuperEconomy'
    resources :lux, controller: 'wagons', type: 'Lux'
  end

  root 'searches#show'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :trains
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes

  validates :name, presence: true
  validate :stations_count

  before_validation :set_name
  after_validation :set_station_number

  private

  def set_name
    self.name = "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  def stations_count
    errors.add(:base, 'Route should contain at least 2 stations') if railway_stations.size < 2
  end

  def set_station_number
    railway_stations_routes.each_with_index { |station, index| station.number = index + 1 }
  end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to [:admin, @route], notice: 'Route was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to admin_routes_path
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path
  end

  private

  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end

  def set_route
    @route = Route.find(params[:id])
  end
end

app/views/admin/routes/_form.html.erb
<%= form_for [:admin, route], html: { style: "display: #{hidden ? 'none' : 'block'}" } do |f| %>
  <%= render 'common/errors', resource: route %>

  <div class="field">
  	<%= f.label :railway_station_ids %>
  	<%= f.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true, class: 'form-control' } %>
  </div>

  <div class="actions">
    <%= f.submit t('.submit', action: route.new_record? ? 'Create' : 'Edit'), class: 'btn-lg btn-info' %>
  </div>
<% end %>

app/views/admin/routes/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', route: @route %>

<%= link_to t('common.show'), [:admin, @route] %> |
<%= link_to t('common.back'), admin_routes_path %>

app/views/admin/routes/index.html.erb
<div class="text-center">
  <h1><%= t('.title') %></h1>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td>
          <div id="route_name_<%= route.id %>">
            <%= route.name %>
          </div>
          <%= render 'form', route: route, hidden: true %>
        </td>
        <td><%= link_to t('common.show'), [:admin, route] %></td>
        <td><%= link_to t('common.edit'), '', class: 'edit_route', data: { route_id: route.id }  %></td>
        <td><%= link_to 'Delete', [:admin, route], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Route', new_admin_route_path %>

app/views/admin/routes/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', route: @route, hidden: false %>

<%= link_to t('common.back'), admin_routes_path %>

app/views/admin/routes/show.html.erb
<p>
  <strong><%= t('.title') %></strong>
  <%= @route.name %>
</p>

<p>
  <strong>Stations in this route:</strong>
</p>
<p>
  <% if @route.railway_stations.empty? %>
    List is empty
  <% else %>
    <table>
      <thead>
        <tr>
          <td width="100px"><strong>Name</strong></td>
          <td><strong>Arrive Time / Departure Time</strong></td>
          <td><strong>Position in Route</strong></td>
        </tr>
      </thead>
      <tbody>
      <% @route.railway_stations.ordered.each do |station| %>
        <tr>
          <td><%= station.title %></td>
          <td>
            <%= form_tag update_arrive_departure_admin_railway_station_path(station), method: :patch do %>
              <%= time_field_tag :arrive, station.arrive(@route).strftime('%H:%M') %>
              <%= time_field_tag :departure, station.departure(@route).strftime('%H:%M') %>
              <%= hidden_field_tag :route_id, @route.id %>
              <%= submit_tag "Change", class: 'btn-lg btn-info' %>
            <% end %>
          </td>          
          <td>
            <%= form_tag update_position_admin_railway_station_path(station), method: :patch do %>
              <%= number_field_tag :position, station.position(@route) %>
              <%= hidden_field_tag :route_id, @route.id %>
              <%= submit_tag "Change", class: 'btn-lg btn-info' %>
            <% end %>
          </td>          
        </tr>
      <% end %>
      </tbody>
    </table>  
  <% end %>
</p>

<p>
  <strong>List trains on this route:</strong>
</p>
<p>
  <% if @route.trains.empty? %>
    List is empty
  <% else %>
    <ul>
      <% @route.trains.each do |train| %>
        <li><%= train.number %></li>
      <% end %>
    </ul>
  <% end %>
</p>

<%= link_to t('common.edit'), edit_admin_route_path(@route) %> |
<%= link_to t('common.back'), admin_routes_path %>