config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'

  resources :tickets, except: [:edit, :update]
  resource :search, only: [:show, :create]

  namespace :admin do
    resources :trains do
      resources :wagons, shallow: true
    end

    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_arrive_departure, on: :member
    end

    get 'admin/index'
    resources :tickets
    resources :routes
    resources :economy, controller: 'wagons', type: 'Economy'
    resources :comfort, controller: 'wagons', type: 'Comfort'
    resources :super_economy, controller: 'wagons', type: 'SuperEconomy'
    resources :lux, controller: 'wagons', type: 'Lux'
  end

  root 'searches#show'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def create
    @initial_station = RailwayStation.find(params[:initial_station])
    @final_station = RailwayStation.find(params[:final_station])
    @routes = (@initial_station.routes & @final_station.routes).compact.uniq
    render :show
  end

  def show
    @routes = [nil]
  end
end

app/views/searches/show.html.erb
<h1>Search Ticket</h1>

<div class="row">
<%= form_tag search_path, class: 'search_form' do %>
  <div class="col-md-5"> 
    <%= select_tag :initial_station, options_from_collection_for_select(RailwayStation.all, :id, :title), class: 'form-control' %>
  </div>
  <div class="col-md-5"> 
    <%= select_tag :final_station, options_from_collection_for_select(RailwayStation.all, :id, :title), class: 'form-control' %>
  </div>
  <div class="col-md-2"> 
    <%= submit_tag 'Search', class: 'btn-lg btn-info btn-block' %>
  </div>
<% end %>
</div>

<p>
  <% if @routes.empty? %>
    <p>Route unknown</p>
  <% else %>     
      <% @routes.compact.each do |route| %>      
        <h4><%= route.name %></h4>
        <% route.trains.each do |train| %>
              <ul class="list-group">                
                  <li class="list-group-item">
                    <%= "Train №#{train.number}"%> |
                    <%= link_to 'Buy Ticket', new_ticket_path(train_id: train.id, initial_station_id: @initial_station.id, final_station_id: @final_station.id) %><br>
                    <%= "Departure: #{route.railway_stations.ordered.first.departure(route).strftime('%H:%M')} /
                     Arrive: #{route.railway_stations.ordered.last.arrive(route).strftime('%H:%M')}" %>
                  </li>              
              </ul>
        <% end %>
      <% end %>    
  <% end %>
</p>