config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'

  resources :tickets, except: [:edit, :update]
  resource :search, only: [:show, :create]

  namespace :admin do
    resources :trains do
      resources :wagons, shallow: true
    end

    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_arrive_departure, on: :member
    end

    get 'admin/index'
    resources :tickets
    resources :routes
    resources :economy, controller: 'wagons', type: 'Economy'
    resources :comfort, controller: 'wagons', type: 'Comfort'
    resources :super_economy, controller: 'wagons', type: 'SuperEconomy'
    resources :lux, controller: 'wagons', type: 'Lux'
  end

  root 'searches#show'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/train.rb
class Train < ActiveRecord::Base
  belongs_to :route
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  has_many :tickets
  has_many :wagons

  validates :number, presence: true

  def count_seats(wagon_type, seats_type)
    wagons.where(type: wagon_type).sum(seats_type)
  end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def edit
  end

  def create
    @train = Train.new(train_params)
      if @train.save
        redirect_to [:admin, @train], notice: 'Train was successfully created.'
      else
        render :new
      end
  end

  def update
    if @train.update(train_params)
      redirect_to admin_trains_path
      else
        render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to admin_trains_path
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :head, :current_station_id, :route_id)
  end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.erb
<%= form_for [:admin, train], html: { style: "display: #{hidden ? 'none' : 'block'}" } do |f| %>
  <%= render 'common/errors', resource: train %>

  <div class="field">
    <%= f.text_field :number, placeholder: 'Number', class: 'input-lg' %>
  </div>

  <div class="field">
    <%= f.label :route %>
    <%= f.select :route_id, options_from_collection_for_select(Route.all, :id, :name), {}, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label 'Head --> Tail' %>
    <%= f.check_box :head %>
  </div>  

  <div class="actions">
    <%= f.submit t('.submit', action: train.new_record? ? 'Create' : 'Edit'), class: 'btn-lg btn-info' %>
  </div>
<% end %>

app/views/admin/trains/_train.html.erb
<tr>
  <td>
    <div id="train_number_<%= train.id %>">
      <%= train.number %>
    </div>  
    <%= render 'form', train: train, hidden: true %>
  </td>
  <td><%= link_to t('common.show'), [:admin, train] %></td>
  <td><%= link_to t('common.edit'), '', class: 'edit_train', data: { train_id: train.id }  %></td>
  <td><%= link_to 'Delete', [:admin, train] , method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/trains/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', train: @train  %>

<%= link_to t('common.show'), [:admin, @train] %> |
<%= link_to t('common.back'), admin_trains_path %>

app/views/admin/trains/index.html.erb
<div class="text-center">
  <h1><%= t('.title') %></h1>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @trains %>    
  </tbody>
</table>

<%= link_to 'New Train', new_admin_train_path %>

app/views/admin/trains/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', train: @train, hidden: false %>

<%= link_to t('common.back'), admin_trains_path %>

app/views/admin/trains/show.html.erb
<p>
  <strong><%= t('.title') %></strong>
  <%= @train.number %>
</p>

<p>
  <strong>Route:</strong>
  <% if @train.route.present? %>
    <%= @train.route.name %>
  <% else %>
    unknown
  <% end %>
</p>

<p>
  <strong>Wagons quantity:</strong>
  <%= @train.wagons.count %><br>
  Super Economy: <%= @train.wagons.super_economy.size %><br>
  Economy: <%= @train.wagons.economy.size %><br>
  Comfort: <%= @train.wagons.comfort.size %><br>
  Lux: <%= @train.wagons.lux.size %>
</p>

<p>
  <strong>Seats quantity:</strong><br>
    <strong>Super Economy:</strong><br>
    Economy Bottom Seats: <%= @train.count_seats(SuperEconomy, :economy_bottom_seats) %>
  <p>
    <strong>Economy:</strong><br>
    Bottom Seats: <%= @train.count_seats(Economy, :bottom_seats) %><br>
    Top Seats: <%= @train.count_seats(Economy, :top_seats) %><br>
    Side Bottom Seats: <%= @train.count_seats(Economy, :side_bottom_seats) %><br>
    Side Top Seats: <%= @train.count_seats(Economy, :side_top_seats) %>
  </p>
  <p>
    <strong>Comfort:</strong><br>
    Bottom Seats: <%= @train.count_seats(Comfort, :bottom_seats) %><br>
    Top Seats: <%= @train.count_seats(Comfort, :top_seats)  %>
  </p>
    <strong>Lux:</strong><br>
    Bottom Seats: <%= @train.count_seats(Lux, :bottom_seats) %>
</p>

<p>
  <strong>Wagons:</strong>
  <ul>
    <% @wagons = @train.head ? @train.wagons.ordered : @train.wagons.ordered_desc %>
    <% @wagons.each do |wagon| %>
      <li><%= link_to "Wagon №#{wagon.number} (#{wagon.type})", [:admin, wagon] %> |
      <%= link_to 'Delete', [:admin, wagon], method: :delete, data: { confirm: 'Are you sure?' } %></li>
    <% end %>
  </ul>
</p>

<p>
  <%= link_to "Add Wagon", new_admin_train_wagon_path(@train) %>
</p>

<%= link_to t('common.edit'), edit_admin_train_path(@train) %> |
<%= link_to t('common.back'), admin_trains_path %>