config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'

  resources :tickets, except: [:edit, :update]
  resource :search, only: [:show, :create]

  namespace :admin do
    resources :trains do
      resources :wagons, shallow: true
    end

    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_arrive_departure, on: :member
    end

    get 'admin/index'
    resources :tickets
    resources :routes
    resources :economy, controller: 'wagons', type: 'Economy'
    resources :comfort, controller: 'wagons', type: 'Comfort'
    resources :super_economy, controller: 'wagons', type: 'SuperEconomy'
    resources :lux, controller: 'wagons', type: 'Lux'
  end

  root 'searches#show'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.erb
<div class="navbar-fixed-bottom">
  <div class="navbar-inner">
    <div class="container">
      <p><strong>The training project in <a href="http://www.thinknetica.com/">online-school Thinknetica</a>
      by <a href="http://www.github.com/pedrogabriel69">Gabriel Pedro</a>, 2016</strong></p>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Railscanner', root_url, class: "navbar-brand" %>
    </div>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Search Ticket", search_path %></li>       
            <li><%= link_to 'My Tickets', tickets_path(@ticket) %></li>
            <% if current_user.admin? %>
              <li><%= link_to "Stations", admin_railway_stations_path %></li>
              <li><%= link_to "Routes", admin_routes_path %></li>
              <li><%= link_to "Trains", admin_trains_path %></li>
              <li><%= link_to 'Tickets', admin_tickets_path(@ticket) %></li>
            <% end %>                                  
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete, confirm: "Are you sure?" %></li>
          <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      <% if user_signed_in? and current_user.admin? %>
        <%=  "Admin - Railscanner" %>
      <% else %>
        <%=  "Railscanner" %>
      <% end %>
    </title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->
        <div class="navbar-fixed-bottom">
          <p>The training project in <a href="http://www.thinknetica.com/">online-school Thinknetica</a>
          by <a href="http://www.github.com/pedrogabriel69">Gabriel Pedro</a>, 2016</p>
        </div>
      </div> <!-- /container -->
  </body>
</html>